Cyan4973/xxHash

Makefile, xxhsum.c
This PR is related to @beckermr's PR #21.  Since it's simple and has many possibility to extend such as multi processing by `xargs`, I don't say this PR replaces PR #21.
This PR adds the following command line switches
- `-c`/`--check` : read XXH32/64 sums from FILEs and check them.
- `--quiet` : Don't print OK.
- `--status` : Don't output anything to stdout/stderr.
- `--strict` : Treat any invalid line as error.
- `--warn` : Show warning message for invalid line.
- If all checksum procedures are succeeded, exit code is 0.
- Otherwise exit code is 1.
```
./xxhsum * > my.xxhash
cat my.xxhash
./xxhsum -c my.xxhash
./xxhsum -H0 * > my.xxhash32
cat my.xxhash32
./xxhsum -c my.xxhash32
```
- `xxhsum -c` mimics `md5sum -c`.
- If we have no idea, follow `md5sum`.
- `xxhsum -c` should accept, all …
=> Add command line switch "-c"/"--check"

Makefile, xxhsum.1, xxhsum.1.md
This PR adds ROFF format manpage `xxhsum.1`.  Also `xxhsum.1` will be genareted from Markdown file `xxhsum.1.md` by [ronn](https://github.com/rtomayko/ronn).
You can generate `xxhsum.1` by the following procedure
```
sudo apt-get install -y ruby-ronn
make man
make preview-man
```
To keep it simple, all `Makefile` targets are written in explicit fashion.
`Makefile` has the following tricky part:
```
xxhsum.1: xxhsum.1.md
cat $^ | $(MD2ROFF) $(MD2ROFF_FLAGS) | sed -n '/^\.\\\".*/!p' > $@
```
Last `sed` command removes `ronn`'s comment lines (`ronn`'s version, author, URL).  It doesn't mean disrespect for `ronn`.  We need this removal because we must keep independent `xxhsum.1` from `ronn`'s version.
- This PR adds external dependency for `ronn`.
- Here is a tradeoff.
- It requires ruby and …
=> Add manpage and its markdown source

Makefile, xxhsum.1, xxhsum.1.md, xxhsum.c
This PR is follow up of PR #55.  All commits are trivial.
- Fix XXHSUM_VERSION in Makefile
- Add the following options to mimic `md5sum`
- `-w` : alias of `--warn`
- `--version` : alias of `-V`
- `--help` : alias of `-h`
=> Add -w, --version, --help and fix XXHSUM_VERSION

cmake_unofficial/CMakeLists.txt
Add cmake option BUILD_SHARED_LIBS to prevent building shared library on static target.
Previous attempt: https://github.com/Cyan4973/xxHash/pull/73
=> install .dll to bin/ instead of lib/

xxhash.c
GCC_VERSION is quite a common macro name, and might clash with already
defined macros. It's safer to use a XXH_ prefix.
I've seen LZ4 does the same, I therefore submitted a simple pull-request to apply the same in xxHash.
Continuation of #82.
=> Replace GCC_VERSION with XXH_GCC_VERSION

cmake_unofficial/CMakeLists.txt
As well as some general tidying up, this also allows the cmake build to compile the xxhsum binary,
=> Build the xxhsum binary with cmake as well

xxhash.c
XXH64_endian_align() has a compile issue using XXH_ACCEPT_NULL_INPUT_POINTER, because it declares 
`const BYTE* const bEnd = p + len;`
and then tries to assign to it again with the line `bEnd=p=(const BYTE*)(size_t)32;`
XXH32_endian_align() avoids this issue by declaring `const BYTE* bEnd = p + len;` (notice the pointer itself is non-const here)
I have not looked much into this, just made the most obvious change to get it to work.
=> Fix minor compile error using XXH_ACCEPT_NULL_INPUT_POINTER

xxhash.c
The last p32++ is unnecessary. It's a minor fix.
=> Remove unused update on local variable p32

xxhsum.1.md
This unhides the arguments, as the `<>` were making them be interpreted as html.
=> xxhsum.1.md: make arguments part of the command

Makefile, README.md, xxhash.c, xxhash.h, xxhsum.c
Hello,
I just fixed a very trivial typo, {32,64}-bits => {32,64}-bit.
And I made another luajit version of xxHash, https://github.com/sjnam/luajit-xxHash .
=> fix a trivial typo

xxhash.c
On Windows, the Intel compiler is closer to MSVC rather than GCC and
does not support the GCC attribute syntax.
---
See lz4/lz4#468.
=> intel: do not use __attribute__((packed)) on Windows

index.html
Previously the links for factorcode and NVBIO were switched around. This fixes that and neatens up the indentation.
=> Fix reversed links for NVBIO and Factor

Makefile, xxhsum.1.md
Their presence caused my tests to fail. I hereby put all my changes
under PD/CC0/Expat licence.
=> Remove trailing whitespace with a check/test.

cmake_unofficial/CMakeLists.txt
Copied over the CMake stuff from LZ4, simplified a bit (no pkg-config, etc.).
I haven't tested very thoroughly, but it's pretty simple.  @ChrisKitching, since I know you're interested in the CMake support maybe you'd like to take a look?
=> cmake: rewrite based on LZ4's CMake support

Makefile
- more warnings enabled (inspired by `zstd` list)
- `-fPIC` is a `CFLAGS` rather than an `LDFLAGS` flag
(though it doesn't change the outcome, since everything is compiler in a single command line)
=> minor Makefile improvements

cmake_unofficial/CMakeLists.txt, xxhash.h
When I wanted to build xxHash on Windows with MSVC (Visual Studio 15 2017) and CMake, I got some linkage errors about xxhsum could not find the file xxhash.lib.
And it was normal because when MSVC build a shared library, it doesn't set every symbols to public like GCC. So the export/import declaration was missing for MSVC and it couldn't build the file xxhash.lib because for it there wasn't anything to export.
So, I added the missing export/import declaration for MSVC in `XXH_PUBLIC_API` and, for compilation in `shared` mode, the definition of `XXH_EXPORT` to tell xxHash to export the symbols or to import them when using the library.
=>  Added export of public symbols on Windows. 

xxh3.h
Decided to move to a new PR.
OK, huge performance improvements found for aarch64.
Apparently, aarch64 **hates** shuffling with a passion and a pride. Even more than armv7a which wasn't so fond of it in the first place.
Using `vshrn`/`vmovn` is almost always faster than `vzip`/`vld2`. It also doesn't freak out GCC 6 so I can remove the warning.
```
./xxhsum 0.6.6 (64-bits little endian), by Yann Collet
Sample of 100 KB...
XXH32               :     102400 ->    38082 it/s ( 3718.9 MB/s)
XXH32 unaligned     :     102400 ->    37847 it/s ( 3696.0 MB/s)
XXH64               :     102400 ->    25979 it/s ( 2537.0 MB/s)
XXH64 unaligned     :     102400 ->    25971 it/s ( 2536.2 MB/s)
XXH3_64bits         :     102400 ->    66295 it/s ( 6474.2 MB/s)
XXH3_64b unaligned  :     102400 ->    65166 it/s …
```
=> Improve aarch64 performance

Makefile, xxh3.h, xxhash.c
Inline assembly is the only thing that works on Clang to stop it from vectorizing XXH32 because it is literally impossible to do so. This lets us (well, not me…) use the AVX2 version of XXH3 without worrying about XXH32, and lets us remove the Makefile hack.
=> better uint128_t multiply for 32-bit, MSVC multiply intrinsics, and fix XXH32 SSE4 bug

xxh3.h
Clang doesn't unroll the XXH3_accumulate loop for some reason. Using `#pragma clang loop unroll(enable)` to hint to Clang that it should unroll results in a huge 1.4-1.5x speedup.
Before: 
```
XXH3_64bits         :     102400 ->   162910 it/s (15909.2 MB/s)
XXH3_64b unaligned  :     102400 ->   140762 it/s (13746.3 MB/s)
```
After:
```
XXH3_64bits         :     102400 ->   215992 it/s (21093.0 MB/s)
XXH3_64b unaligned  :     102400 ->   188791 it/s (18436.6 MB/s)
```
=> Add unroll pragma for Clang in XXH3_accumulate.

.travis.yml, appveyor.yml, tests/bench/Makefile, tests/bench/timefn.c
```
$ LC_ALL=C make
cc -O3 -Wall -Wextra -Wstrict-aliasing=1 -I../..  -c -o timefn.o timefn.c
timefn.c:123:1: error: unknown type name 'U64'
U64 UTIL_getSpanTimeMicro(UTIL_time_t clockStart, UTIL_time_t clockEnd) { return 1000000ULL * (clockEnd - clockStart) / CLOCKS_PER_SEC; }
^~~
timefn.c:123:5: error: conflicting types for 'UTIL_getSpanTimeMicro'
U64 UTIL_getSpanTimeMicro(UTIL_time_t clockStart, UTIL_time_t clockEnd) { return 1000000ULL * (clockEnd - clockStart) / CLOCKS_PER_SEC; }
^~~~~~~~~~~~~~~~~~~~~
In file included from timefn.c:14:0:
timefn.h:79:7: note: previous declaration of 'UTIL_getSpanTimeMicro' was here
PTime UTIL_getSpanTimeMicro(UTIL_time_t clockStart, UTIL_time_t clockEnd);
^~~~~~~~~~~~~~~~~~~~~
timefn.c:124:1: error: unknown type name 'U64'
U64 …
```
=> xxhash-bench: fix U64/PTime confusion.

xxh3.h
Small change to the usage of XXH_mult32to64 in xxh3.h that fixes the C4244 warning in MSVC.
- Fixed warning C4244 conversion from 'XXH64_hash_t' to 'unsigned int', possible loss of data
=> MSVC Fixed warning C4244 in xxh3.h

xxh3.h
* XXH3_accumulate has the better documented version for neon
* XXH3_scrambleAcc works properly now
* XXH3_accumulate's scalar version uses 64-bit types for better performance on 64-bit targets
* Added the restrict keyword to acc to prevent any reloads
* Removed the aarch64 mult128 code; GCC would never reach it anyways
* Disabled forced unrolling on ARM Clang, it is detrimental to performance.
=> ARM and scalar improvements/fixes

xxh3.h
=> update intrinsic include policy to be compatible with gcc < 4.4 

xxh3.h
Detecting SSE2 instructions on Visual Studio when it's compiling for x86 32-bit needs to be done by yet another macro, see https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019
The change turns performance graph from the red line into the blue one.
Somewhat related to things discussed at #211
=> Detect SSE2 on MSVC 32 bit as well

xxh3.h
ALIGN is a common name that may be defined before xxh3.h is included.
=> Rename ALIGN to XXH_ALIGN

.travis.yml, xxh3.h, xxhash.h, xxhsum.c
Makes it possible to provide an arbitrary secret blob of bytes (of minimum size `XXH_SECRET_SIZE_MIN`) to make it more difficult for an external actor to generate a collision without knowing the secret.
Also : clarifies the role of the `seed`, which is a required preliminary for the streaming implementation.
This version also features a dramatic performance improvement under Visual 2019 with `AVX2` enabled.
=> XXH3_64bits_withSecret()

xxh3.h, xxhsum.c
provides guarantee of no collision for 2 different inputs of same len <= 8 .
=> xxh3: updated formula for len 1-8

xxh3.h
I was testing the non-streaming XXH3 on 512 byte block, and a streaming API that happened to do a "3 bytes update, then 509 bytes update", and the result was different. Looks like `bufferedSize` was not properly updated if the incoming block size landed exactly on multiple of the internal buffer size. With this proposed fix it seems to be better.
=> Fix XXH3 streaming result when update block size happens to land exactly on buffer size/

xxh3.h, xxhash.h
- seems to produce same results as non-streaming functions,
- the 128-bit non-streaming ones don't support "custom secret", so
neither does the streaming variant
- the 64-bit functions seem to do something more clever in order to
avoid leaking the key/secret, which none of current 128-bit functions
do
- the naming of the streaming functions is a bit weird now, since
most of the ones with "64" in the name are what should be used in
128 bit case too
=> Initial attempt at 128-bit XXH3 streaming variant

xxhash.c
Was wrong for length == 4 on 32-bit platforms
=> Fixed rerolled version of 64-bit hash. 

Makefile, xxh3.h, xxhash.c
control their activity with `DEBUGLEVEL=#`,
automatically test `assert()` as part of `make test`.
fix #233
=> fixed assert()

.gitignore, cmake_unofficial/CMakeLists.txt, cmake_unofficial/README.md
Hello!
>For historical reasons in CMake 3.12 and below the `option()` command removes a normal (non-cached) variable
>of the same name when:
>
>- a cache entry of the specified name does not exist at all, or
>- a cache entry of the specified name exists but has not been given a type (e.g. via `-D<name>=ON` on the command line).
I've replaced `option()` commands with `set(... CACHE ...)` for build options (`BUILD_XXHSUM` and `BUILD_ENABLE_INLINE_API`) in order to provide possibility to hardcode build options (within downstream project) in BUNDLED_MODE with normal `set()` (for CMake < 3.13).
Also i've prefixed these options with `XXHASH_` for convenience.
Fixes bundled mode determining logic and makes `XXHASH_BUNDLED_MODE` overridable cached var which can be set from downstream projects. …
=> Cmake opts

.travis.yml, xxh3.h, xxhsum.c
This fixes VSX support and reduces the requirement to POWER8. 
Additionally, Travis now performs CI tests on VSX code and ARM NEON code. 
See https://github.com/Cyan4973/xxHash/pull/244 for details
=> [PPC64][TRAVIS] Fix VSX + add POWER8 support, fix VSX and ARM NEON Travis testing

xxhash.c
Clang was using ldmia and ldrd on unaligned pointers on ARMv6. These instructions don't support unaligned access.
When `-munaligned-access` is used, this will emit normal ldr sequences which do support unaligned access.
I also check the numerical value of __ARM_ARCH.
=> Prevent Clang from emitting unaligned ldm/ldrd on ARMv6, better arm macros

.gitignore, appveyor.yml, cmake_unofficial/CMakeLists.txt, xxh3.h, xxhash.c, xxhash.h
now generates an error when Visual compiler emits a warning
also fix a few corresponding minor warnings on Visual.
fix #249
=> Visual Studio tests on Appveyor

README.md, xxh3.h, xxhash.c
Sorry about the disorganized commit. :(
Yet again, I had to fix ARMv6. Clang went from ldm to ldrd which also bus errors.
Therefore, I decided to fix the root problem and remove the `XXH_FORCE_DIRECT_MEMORY_ACCESS` hack, using only memcpy.
This will kill alignment memes for good, and besides, it didn't seem to make much of a difference.
Additionally, I added my better 128-bit long multiply and applied DRY to `XXH3_mul128_fold64`. This also removes the cryptic inline assembly hack, as UMAAL is properly generated now.
Each method was documented, too (we need more comments).
Also, I added a warning for users who are compiling Thumb-1 code for a target supporting ARM instructions.
While all versions of ARM and Thumb-2 meet XXH3's base requirements, Thumb-1 does not.
First of all, UMULL is …
=> Better 128-bit multiply, multiple bugfixes.

xxh3.h, xxhsum.c
ensure that each input stripe immediately impacts 128-bit of state
(instead of later at junction stage).
=> improve xxh128 for mid-size

xxh3.h, xxhash.c, xxhash.h
Part of my multipart patch.
This reduces type erasing and casting to wider types.
All unaligned pointers are passed as `BYTE` if possible, with public APIs casting to it immediately instead of after. I'm not sure if we should use it with the SSE2 code because Intel messed up `_mm_loadu_si128`'s prototype.
=> Reduce void pointers and evil casts.

xxhsum.c
Previously, XXH3_64bits looked much faster than XXH3_128bits. The truth
is that they are similar in long keys. The difference was that
XXH3_64b's benchmark was unseeded, putting it at an unfair advantage
over XXH128 which is seeded.
I don't think I am going to do the dummy bench. That made things moe
complicated.
=> Use both seeded and unseeded variants in the bench

xxh3.h, xxhash.c, xxhash.h, xxhsum.c
Fixes #258.
```c
BYTE -> xxh_u8
U32  -> xxh_u32
U64  -> xxh_u64
```
Additionally, I hopefully fixed an issue for targets where int is 16
bits. XXH32 used unsigned int for its seed, and in C90 mode, unsigned
int as its U32. This would cause truncation issues. I check limits.h in
C90 mode to make sure UINT_MAX == 0xFFFFFFFFUL, and if it isn't, use
unsigned long.
We should see if we can set up an AVR CI test. Just to run the
verification program, though, as the benchmark will take a very long
time.
Lastly, the seed types are XXH32_hash_t and XXH64_hash_t for XXH32/64.
This matches xxhash.c and prevents the aforementioned 16-bit int bug.
=> Improve typedefs, fix 16-bit int/seed type bug

.travis.yml
This offloads the Arm64 and PPC64le builds and tests to real hardware that is now available on Travis CI.
=> Use Travis CI Arm64 and PPC64le arch

.travis.yml, xxh3.h, xxhsum.c
~~This is not ready to merge, it has only been tested for compile errors at the moment. I don't have an s390x toolchain, just Clang's cross compiler.~~
- Add s390x support to xxhsum
- Reuse the VSX path for s390x, they both use similar APIs
- Replace vec_vsx_ld with memcpy
- Remove vpermxor hack, it makes things too messy
- Improve Travis tests, dump CPUID info
=> Unified VSX and S390X code path, remove vpermxor 

tests/bench/benchfn.c, xxhsum.c
nothing terribly important, just some clean up.
Also : a few `cppcheck` warnings are plain false positives with no obvious replacement, in which case, no code modification is performed.
=> fixed a bunch of minor cppcheck warnings

xxh3.h
When gcc was updated to version 10 in Fedora the build of the xxhash
package started failing. The compilation succeeds, but the checks
trigger an error. This change, suggested by the maintainers of the gcc
package in Fedora, addresses the issue. F0r details see:
https://bugzilla.redhat.com/show_bug.cgi?id=1798908
=> gcc10 altivec

xxhsum.c
it's not useful : cygwin already uses the `posix` code path
fix #100
=> removed cygwin code path

README.md, xxhash.h
This marks all internal functions as `static`, and gives the compiler full control over whether to inline functions or not.
This is automatically defined on GCC and Clang when `-O0`, `-Os`, `-Oz`, or `-fno-inline` is used.
With clang -Oz for AArch64, the .text section goes from 16880 bytes to 8136 bytes.
=> Implement XXH_NO_INLINE_HINTS to disable forced inlining.

xxh3.h
AArch64 and ARMv7 now use the same codepath, with the VZIP.32 hack being
abstracted away in a macro.
I also fully (over?) documented it to explain the hack (as well as make a note of the use of `vmull_u32` instead of `vmul_u32` in `XXH3_scrambleAcc` to work around a bug in Clang 6 and 7).
=> Unify NEON code, fully document the VZIP.32 hack.

Makefile, tests/Makefile, tests/multiInclude.c, xxh3.h, xxhash.c, xxhash.h, xxhsum.c
Inlining hash functions is generally beneficial for performance. The benefit becomes critically important whenever input size can be defined as a compile-time constant.
To inline xxhash functions, one just needs to include it this way :
```
#define XXH_INLINE_ALL
#include "xxhash.h"
```
One potential issue is that `xxhash.h` may have already been included previously,
typically as part of another included `*.h` .
In which case, the second `#include` statement will have no effect : the content of `xxhash.h`, having already been parsed, would be skipped.
This patch fixes this situation :
now, when `XXH_INLINE_ALL` is defined, all identifiers are renamed,
in order to avoid naming collisions and confusion with already included identifiers.
The renaming process uses `XXH_NAMESPACE`.
For this to …
=> xxhash can be inlined even when previously included

xxh3.h, xxhash.h, xxhsum.c
Following suggestion from @pdillinger, at https://github.com/Cyan4973/xxHash/issues/175#issuecomment-548108921 .
The probability of receiving an empty string is larger than random (> 1 / 2^64),
making its generated hash value "more common".
For some algorithm, it's an issue if this "more common" value is 0.
Maps it instead to an avalanche of an arbitrary start value (prime64).
The start value is blended with the `seed` and the `secret`,
so that the result is dependent on those ones too.
It makes the return value of "empty string" no longer comparable with `0.7.2`.
For this reason, the internal library version number is updated to `0.7.3`.
=> return non-zero on empty string :

README.md, xxh3.h, xxhash.h
- Fix older GCC versions not liking `__attribute__((aligned))` before struct members
- Use downcast+upcast instead of mask for `XXH_mult32to64`, as some old compilers don't understand the mask pattern
- Add a third memory access which uses byteshifting; this is recommended for old compilers which don't inline `memcpy()` or big-endian systems without a native byteswap instruction
- Force GCC to use -O2 in xxh3.h in AVX2 mode to prevent overzealous unrolling
- Document GCC's AVX2 load splitting
=> Compiler specific fixes

xxh3.h, xxhsum.c
This is an iteration over #307 .
The motive is that #307 give up mixing bits at `len==8`, on the ground that it cannot completely recover from space contraction, and therefore delegate that length to the now extended `8to16` segment. The issue is that the performance for `len==8` is now "bad" (or "less good") on 32-bit and ARM platform.
However, the 4to7 mixer, based on `mul32to64`, was "not so far" on quality even on 64-bit input, passing all tests bar one, and by a relatively small margin. So this variant tries to fix the remaining issue, located in the extended `DiffDist` test dealing with partial extraction of bitfields.
It improves the small bias in the lower bits by using a more complex insertion policy, in order to feed `input` directly in the upper region, before the avalanche.
It …
=> Last variant for the 4to8 segment (mul32to64)

.gitignore, Makefile, tests/Makefile, tests/generate_unicode_test.c, tests/multiInclude.c, xxhsum.c
- Unicode filenames should now work, with a method that works with and without Unicode mode on Windows.
- Added a test in the Makefile.
- Use unbuffered stderr output on Windows, fixes output not updating immediately on MinGW.
- Fix some missing `$(EXT)`s in the Makefile, causing Clang to emit `xxhsum` instead of `xxhsum.exe` on Windows, as well as xxhsum's rule ignoring `$(FLAGS)`.
=> Fix Unicode support on Windows, minor Windows tweaks

xxh3.h
This new version is much simpler than `v0.7.2` for len [4,8].
It replaces most of the multiplications by a 64x64->128 one, which feels adequate for a 128-bit hash.
As a consequence, it runs faster on `x64` systems. Even `aarch64` prefers it.
Note however that speed on 32-bit `x86` is negatively impacted.
In the context of `xxh128`, I'm not sure though if this is a relevant platform to optimize for.
Latency test, fixed size inputs [4-8] , performance reported in Millions of Hashes per Second (MH/s) :
| arch | cpu | compiler | v0.7.2 | this PR | 
| --- | --- | --- | --- | --- | 
| `x64` | i7-8559U | Apple clang 11.0 |  130 |  161 | 
| `x64` | i7-9700K | gcc v9.2.1 | 114 | 137 | 
| `x86` | i7-9700K | gcc v9.2.1 | 83 | 73 | 
| `aarch64` | snapdragon 855 | clang v9.0.1 | 89 | 94 |  
| …
=> Simplify len [4,8] for xxh128

xxh3.h
- Add some explanations of the algorithms
- show 128-bit arithmetic in `9to16_128b`
- show pieced together inputs in `1to3`
- Mention the mum/farsh/umac influence
- Add Google's comment about 32->64 multiply mixing quality in `XXH3_scrambleAcc`
- Mention the switch from iterative to single shot in short hashes
- Make the SIMD comments match and look cleaner
- remove ancient farsh comments
- move `_mm_shuffle_epi32` to its own line
- no `_mm_shuffle_epi32` magic numbers
- Minor typo fixes
- Be transparent about the mid range collisions (unless we want to fix it which AFAIK is not planned)
- don't see any reason to deny its existence, nothing is perfect
- explain the unlikely probability compared to umac collisions
- note that XXH128 isn't affected
- use `xxh_` prefix on VSX typedefs to …
=> Improve documentation of internals

xxh3.h
Insert `secret` from `input_hi` only, to avoid `xor` cancellation,
as suggested by @easyaspi314 .
Also, simplified a bit the next instructions,
resulting in a small improvement to distribution qualities.
Surprisingly, while I tested variants simplifying even more,
replacing the following larger multiplications by 2 smaller `mult32to64` ones,
or even a single one with some additional `xorshift`,
it would not result in any measurable speed benefit.
So I settled on this variant.
Long tests ongoing. No surprise expected, this variant already pass the most difficult ones.
=> xxh128 len[9-16] : small simplification

xxh3.h, xxhsum.c
Just some minor fixups.
Arch detection:
- MSVC x86 no longer shows up as `unknown`
- x86_64 and aarch64 always show `SSE2` and `NEON` respectively
- ARM gives more detail:
- unaligned access
- arch version (only number though)
- thumb/thumb-2
- example:
- `ARMv6 + unaligned`
- `ARMv4 + Thumb-1`
- would previously show up as `arm` despite being entirely different
`9to16_128b`:
- Comments updated, switched to line-by-line because the whole thing isn't 128-bit arithmetic
- The `input_hi + XXH_mult32to64((xxh_u32)input_hi, PRIME32_2 - 1)` line is documented in detail
- shows the usage of distributive property etc
- Add a second 32-bit path for said multiply
- Saves a data dependency and an `adc` on 32-bit
- Adds a mask on 64-bit
- More reflective of the actual arithmetic
=> Comments + 32-bit path for 9to16_128b, improve arch detection

xxh3.h, xxhsum.c
This is the design proposed
to better obfuscate `secret` when small inputs are ingested.
In this scenario, an attacker is presumed having both control of the input
and access to the full result of the function, in an effort to retrieve a custom `secret`.
To handle this scenario, the `secret` section which generates the bitflipper
is now a combination of 2 regions of the `secret` (and the `seed`).
The combined regions are different for all inputs sizes from 0 to 16.
Now, even if the bitflipper is retrieved (requiring access to the result of the hash function), it's not possible to directly determine the original values of the `secret` involved in the calculation.
This abstraction has zero cost when used with the default `kSecret`,
as the compiler is expected to combine these regions …
=> Combined secret for small inputs

Makefile, README.md, appveyor.yml, tests/bench/LICENSE, tests/bench/benchHash.c, tests/bench/benchHash.h, tests/bench/bhDisplay.c, tests/bench/bhDisplay.h, tests/bench/hashes.h, tests/bench/main.c, tests/collisions/.gitignore, tests/collisions/LICENSE, tests/collisions/Makefile, tests/collisions/README.md, tests/collisions/allcodecs/README.md, tests/collisions/allcodecs/dummy.c, tests/collisions/allcodecs/dummy.h, tests/collisions/hashes.h, tests/collisions/main.c, tests/collisions/pool.c, tests/collisions/pool.h, tests/collisions/sort.cc, tests/collisions/sort.hh, tests/collisions/threading.c, tests/collisions/threading.h, xxh3.h, xxhash.h
Add a new test tool, the brute-force collision tester,
used to verify the quality of 64-bit hash functions
with regards to collision ratio.
This kind of analysis is out of `SMHasher` range, this it takes many billions of hashes to observe just a few collisions.
The tool requires a huge amount of memory, to store hash values, or even just to filter candidates.
See `README.md` for details.
=> Collision tester

README.md, doc/xxhash_spec.md, tests/bench/benchHash.c, tests/bench/benchHash.h, tests/bench/bhDisplay.c, tests/bench/bhDisplay.h, tests/bench/main.c, tests/collisions/README.md, tests/collisions/hashes.h, tests/collisions/main.c, tests/generate_unicode_test.c, tests/multiInclude.c, xxh3.h, xxhash.c, xxhash.h, xxhsum.1, xxhsum.1.md, xxhsum.c
- Fix many spelling/grammar issues, primarily in comments
- Remove most spaces before punctuation
- Update XXH3 comment
- Wrap most comments to 80 columns
- Unify most comments to use the same style
- Use hexadecimal in the xxhash spec
- Update help messages to better match POSIX/GNU conventions
- Use HTML escapes in README.md to avoid UTF-8
- Mark outdated benchmark/scores
=> [WIP] The Great Typo Hunt

xxh3.h, xxhsum.c
one more time ...
This is (hopefully) the last change for this release.
The recent brute-force collision tester found a weakness right in this range.
The new version is inspired by rrmxmx, and passes all tests with flying colors.
Btw, it also restores bijectivity for 64-bit inputs.
It's also a bit slower (138 - > 125).
I tried to restore its speed, and almost reached it, by replacing the first 2 `rotl` by a single one.
However, invariably, some quality test fail somewhere.
So I got tired of trying and settled on this version.
=> updated len [4-8] for xxh3

xxh3.h
Fix some blatant autovec issues without the need for command line flags. Follow-up to #312.
- Turn on XXH_FORCE_INLINE for XXH3_hashLong on Clang. The scalar path has
no reason to be autovectorized, it would use the other codepaths.
- Fix Clang NEONv7 autovectorization in 129to240_64b
- Fix GCC x86 autovectorization of the long multiply
=> Autovectorization in-source quickfixes

xxhsum.c
Uses an adapted version of the fwprintf wrapper suggested by @t-mat,
and _setmode.
Also tries to work around classic MinGW not defining _O_U8TEXT.
=> Switch stdout/stderr to UTF-8 on Windows

CHANGELOG, tests/collisions/README.md, xxh3.h, xxhsum.c
Improved quality in a few remaining tests
when restricting the analysis to the low 64-bit of `xxh128`.
=> [xxh128] last quality updates

LICENSE, Makefile, tests/bench/Makefile, tests/bench/benchHash.c, tests/bench/benchHash.h, tests/bench/benchfn.c, tests/bench/benchfn.h, tests/bench/bhDisplay.c, tests/bench/bhDisplay.h, tests/bench/hashes.h, tests/bench/main.c, tests/bench/timefn.c, tests/bench/timefn.h, tests/collisions/Makefile, tests/collisions/allcodecs/dummy.c, tests/collisions/allcodecs/dummy.h, tests/collisions/hashes.h, tests/collisions/main.c, tests/collisions/pool.c, tests/collisions/pool.h, tests/collisions/sort.cc, tests/collisions/sort.hh, tests/multiInclude.c, xxh3.h, xxhash.c, xxhash.h, xxhsum.c
- Replace '-present' with '-2020' (fixes #329)
- Use correct format: `Copyright (C) <year> <name of author>`
- Fix some obviously incorrect years from copy/paste i.e. avoid time travel
Feel free to correct any of these if they are wrong, @Cyan4973
=> Fix copyright years

xxh3.h, xxhash.h, xxhsum.c
Thanks, @RedSpah for noticing this.
Previously, the 64-byte alignment of XXH3_state_t was only enforced on the stack, and the lower `malloc` alignment requirements caused crashes with the aligned AVX2/SSE2 loads and stores we assumed we could use.
This change ensures that XXH_malloc returns a 64 byte aligned pointer by manually aligning it. This avoids ugly feature tests and, besides, manual alignment would already be required as a portable fallback.
Dynamically allocated states are now used in the sanity check — this would have immediately pointed out this bug.
Due to the rather serious nature of this bug, it is suggested that this be patched into master and released as a hotfix for v0.7.3.
=> [HOTFIX] Align malloc, use createState/freeState in sanity check

xxh3.h, xxhash.h, xxhsum.c
- Mark RC status in xxh3 comment
- Add XXH128 summary
- Shill XXH3 in XXH32 and XXH64 comments :stuck_out_tongue: 
- Start wrapping the absurdly long lines in xxh3.h
- Minor rearrangements
- ~~Use `xxh_u32` instead of `U32` in `xxhsum.c`~~
- ~~Thought this was already the case...~~
- ~~Don't redefine on XXH_INLINE_ALL~~
- ~~Cleaned up xxhsum bench~~
- ~~Remove copy/paste mess~~
- ~~Make output long enough so we don't cut off on xxHash names~~
- ~~Make it easier to expand~~
=> More documentation and cleanup

xxhsum.c
- Clean up xxhsum benchmark code
- Reformat
- Use a table and a loop to abstract it
- Removes copy/paste mess
- Makes adding new hashes to test trivial
- Fix an incorrect `assert` which just happened to work 
- Add `withSecret` to the benchmark
- Uses a static buffer because it is easier than passing around a secret (is that ok?)
- Generated in the same way as the sanity buffer (it is now in a function)
- Make the output lines long enough to fit the xxHash names.
- Fix some minor issues and remove some unused macros
=> xxhsum bench improvements

tests/collisions/Makefile
- Don't use `-mavx2 -maes` in `collisions`
- Prevents `make test` from passing on non-x86 targets
- ~~Default `$(CC)` to `gcc`~~
- ~~classic mingw32 has `gcc` but not `cc`~~
- Use the more proper `-std` flag instead of `--std`
TODO: proper Windows library flags: bfd accepts Linux flags, but
ld.lld errors on `-Wl,-soname`. Might be a later PR.
=> Minor Makefile fixes

xxhsum.c
Now uses `WriteConsoleW` instead of `vfwprintf`. This is codepage independent and works on Windows XP.
Doing this also avoids the `_O_U8TEXT` hack.
Also use `_vsnprintf` instead of `vsnprintf`, as it is more consistent than `vsnprintf` in that it doesn't write the null terminator on truncation. Weird.
Some minor cleanup was done as well.
=> New Windows Unicode solution, works on XP

xxh3.h, xxhash.h, xxhsum.c
Fixes a few extra minor warnings. 
- Trailing comma in enum in xxhsum.c
- Extra semicolon
- Non-constant brace list initializers
=> Fix a few warnings

xxh3.h
- Move `veorq_u8` below if block, improves interleaving
- Block autovec on ARMv7 in `XXH3_mixAccs`
- Rerolled loop. Doubt it makes a difference, but still worth testing on other platforms/compilers.
- Block constprop on aarch64 in `XXH3_initCustomSecret` to prevent `movk` chaining
=> [ARM/Clang] Minor speed hacks

index.html
lz4-java supports both versions of the algorithm.
I did some benchmarking on lz4-java and OpenHFT zero allocation hashing. The openhft version does *not* implement a streaming version, which makes it useless for big files (those have to be read into memory entirely).
The lz4-java version on the otherhand supports XXH32 and XXH64 and has a streaming version that can be used on big files. Also it has little overhead compared to the C-algorithm (I benchmarked it [here](https://github.com/rhpvorderman/hashtest). In other words: lz4-java is a very good java implementation of xxhash. So I hope that with updating the github page more people will use that particular java implementation in their java projects.
=> Update lz4-java status on github io page.

xxh3.h, xxhash.h, xxhsum.c
on avx512 targets, variant with default secrets will improve 45%. The following result is compiled with `-Ofast -mavx512f`, and there is also no need to add `-mno-avx256-split-unaligned-load` with gcc.
compiling option:
- avx512 gcc-9/clang-9:  `-Ofast -mavx512f`
- avx2 gcc-9: `-Ofast -mavx2 -mno-avx256-split-unaligned-load`
- avx2 clang-9: `-Ofast -mavx2`
```bash
./xxhsum 0.7.4 (64-bit x86_64 + AVX512 little endian), Clang 9.0.0 (tags/RELEASE_900/final), by Yann Collet
Sample of 100 KB...
XXH3_64b                      :     102400 ->   565524 it/s (55227.0 MB/s)
XXH3_64b unaligned            :     102400 ->   565409 it/s (55215.7 MB/s)
XXH3_64b w/seed               :     102400 ->   561795 it/s (54862.8 MB/s)
XXH3_64b w/seed unaligned     :     102400 ->   561556 it/s (54839.5 MB/s) …
```
=> add optimized implementation for AVX512 targets

xxhsum.c
Use `__wgetmainargs()` instead of `GetCommandLineW()` and `CommandLineToArgvW()`. While it is an internal API, aside from declaring the function, it actually simplifies things a lot, as we can setup a `wmain()` equivalent in a few lines.
It also avoids linking to `Shell32.dll`, which is a lot of bloat for a simple command line utility.
Most importantly, this supports wildcards on `cmd.exe`, fixing #341.
Also improved comments and did minor cleanup.
=> Fix Unicode hopefully for the last time

doc/xxhash.cry
I created a specification for xxHash in [Cryptol](https://github.com/GaloisInc/cryptol). I thought it might be nice to include it in the xxHash documentation so developers could test against it. 
Cryptol, if you're not familiar, is an interpreted domain specific language for cryptography. The interpreter allows one to quickly generate test vectors at any part of the algorithm. Cryptol also has a tight binding to SMT solvers, useful for proving properties about such specifications.
This also provides the groundwork for potential future work --- on the off chance someone ever wanted to _prove_ that the optimized xxhash implementation here is correct with regard to a formal specification (à la Amazon's [s2n](http://www0.cs.ucl.ac.uk/staff/b.cook/CAV18_s2n.pdf)), they'd need some formal …
=> Contribute a Cryptol specification of XXH32 and XXH64 to the documentation

Makefile, xxh3.h, xxhash.h
- Every symbol, typedef, and macro is prefixed with `XXH` or `xxh`.
- For compatibility with legacy code that messes with the internals, `XXH_OLD_NAMES` can be defined to wrap old names in macros. This also brings back `U32` and friends.
=> Clean up namespace

xxh3.h, xxhash.h
also fix `XXH3_copyState()`
when copying a state initialized with a `seed`.
fix #365
=> make XXH3_state_t movable

Makefile, xxhsum.1, xxhsum.1.md, xxhsum.c
This makes it way easier to use xxhsum in scripts as a drop-in replacement for sha256sum, md5sum, etc, and stops polluting log files after such replacement. The Loading message also serves no real and demonstrably useful purpose, and messes up with console sometimes, or significantly slows down processing when processing big number of files (10k+).
I am aware of `--quiet` option, but sometimes some tools expect single binary name, not binary with flags, (i.e. `find -exec "xxh64sum --quiet"` will not work). And again, it should be default. All existing popular hash functions don't print such unneeded diagnostics.
=> Remove "Loading..." from source

README.md, xxh3.h
distinguishes :
- `__clang__` : 320
- `AVX512` : 512
- the rest : 384
conflict with #350
=> simplified XXH_PREFETCH_DIST logic

xxh3.h, xxhsum.c
Streaming implementation of `XXH3`/`XXH128` could fail, reporting an incorrect hash value,
for certain specific ranges of length, while ingesting input in segments of random length.
issue reported by @WayneD
fix #378
updated test case to catch this issue
=> fix streaming checksum

xxhsum.c
If fread() fails reading a file, output an error and exit.  The new code
also avoids an update call on a 0-length buffer at end of file.
=> Make xxhsum check if fread() failed

README.md, xxhash.h
as this architecture offers decent performance for unaligned memory accesses (like `x86`/`x64`).
This modification circumvents the problem described in #383,
as the direct read path using `const xxh_u32*` will not be generated by default.
Note however that this does not go at the root of the problem,
which is currently presumed to be related to strict-aliasing
when using the direct read path _and_ inlining `XXH32()`.
This deeper issue however is more difficult to solve without a reproduction case.
I also used this opportunity to fix or reinforce documentation.
=> remove alignment check on aarch64

.gitignore, .travis.yml, Makefile, README.md, xxh3.h, xxh_x86dispatch.c, xxh_x86dispatch.h, xxhash.h, xxhsum.c
Started from a baseline developed by @easyaspi314 (#358),
`xxh_x86dispatch.c` makes it possible to dynamically detect
which vector instruction set is present on the active system
and use the (presumable) best available one,
using this priority order : `avx512` > `avx2` > `sse2` > `scalar`.
3rd party applications willing to employ this ability
just have to `#include "xxh_x86dispatch.h"`.
This header automatically includes `xxhash.h`,
and swap relevant `XXH3`/`XXH128` symbols
with their vector dispatch counterpart.
Only runs on `x86`/`x64`.
Only compiles with `gcc` and `clang`.
added : `make dispatch` target, which compiles `xxhsum` with this new ability.
added : `make xxhsum DISPATCH=1`, which is equivalent to `make dispatch`
=> Intel vector instruction dispatcher

Makefile, xxh_x86dispatch.c, xxhsum.1.md, xxhsum.c
Updated the benchmark module, with following abilities : 
- by default `-b`, benchmark only `XXH32`, `XXH64`, `XXH3` and `XXH128`
+ so that casual users don't get swamped by an avalanche of results
- can get instructed to bench multiple selected variants, using `-b1,2,3,..`
- can bench all variants with `--bench-all` (previous default)
- sub-second evaluation with `-i0`, for a quick check
- added streaming variants `XXH3_stream` and `XXH128_stream`
The last bullet point coupled with `DISPATCH=1` was basically the objective.
This allowed me to observe that streaming performance with `AVX2` is massively less impressive than with one-shot API. Initially, I even thought that the dispatcher was not working, but it is (check addresses, and even enforced variants manually). After multiple tests, …
=> Updated benchmark module

Makefile, xxhsum.c
using a `*` separator as second character,
requested in https://github.com/Cyan4973/xxHash/issues/382#issuecomment-641978062
=> compatibility with turbosfv 

Makefile
- Fix identification of Cygwin/MSYS/MINGW "OS" that have $(OS) of
Windows% but shouldn't obey the Windows rules.
- Add Cygwin to the list of validated installs. I ran install as:
`PREFIX=/usr make install`
- The uninstall target now removes the xxh3.h file.
=> Some Makefile improvements

Makefile, xxh_x86dispatch.h
embedding the `*_dispatch()` symbols into the library.
=> allow optional compilation of libxxhash with DISPATCH=1

Makefile, xxhsum.c
Follows #382
`--tag` is an hidden option for the time being (undocumented)
as it's only an output format,
there is no ability to `-c` check it yet.
The effort was also useful in refactoring part of `xxhsum` code base.
One advantage of the `--tag` BSD format is
that it's a lot safer to introduce additional formats.
For example, little and big-endian variants can co-exist safely,
since endianess is clearly expressed as part of the algorithm name.
It would also make it possible to introduce XXH3 (later),
even though it's 64-bit, which would be confusing with XXH64.
Also :
added ability to select algorithm by specifying bit width.
Hence :
H0 == H32 ==> XXH32
H1 == H64 ==> XXH64
H2 == H128==> XXH128
=> introduced --tag for BSD-style output

xxh3.h, xxhsum.c
fix #344
This modification fixes `demerphq`'s avalanche tests for len [0-3],
(_outdated_) by switching to stronger `rrmxmx` avalanche, already in use for len [4-8].
(_outdated_ ) This is not without consequences : the new variant is ~10% slower in latency, and ~20% slower in bandwidth. That being said, the impact is only felt in the len [0-3] range, so it's pretty limited. Also, the previous function was focused on providing good mixing for (up to) 24-bit of input, while the new one also mixes well the 64-bit `seed`, which is kind of an extended scope.
__Update__ : previous paragraph is no longer correct, new version produces identical perf, by switching to `XXH64` avalanche instead of `rrmxmx`.
The real issue is that this change makes the result of `XXH3()` no longer comparable to …
=> fixed demerphq avalanche tests for len [0-3]

xxh_x86dispatch.c
Make it possible to build xxh_x86dispatch.c with `XXH_DISPATCH_AVX` and/or `XXH_DISPATCH_AVX512` undefined.
=> Dispatch defines

xxh3.h, xxh_x86dispatch.c
So far, `XXH3` and `XXH128` have been using a related yet slightly different mixer.
The main reason is that `XXH128` must spread ingestion over a 128-bit accumulator width, 
while `XXH3` only needs 64-bit, which is easier and slightly faster.
This PR simplifies the mixer, by always using `XXH128` mixer.
This choice comes at the cost of a bit of top speed performance for `XXH3` (~10%).
However, it also provides the following benefits : 
- There was a small gradual degradation in `XXH3` collision ratio, from 64-bit towards 62-bit, when input length increases beyond > 1 KB (it was previously believed that collision ratio would remain stable whatever the input length beyond 256). This PR fixes it.
- Simpler code
- Smaller produced binary (variable impact, depending on compiler settings).
- …
=> Switch mixer to XXH128
