Cyan4973/xxHash

- .gitignore
- xxhash.c
Supersedes pull request #60; this PR targets the dev branch instead of master.
> [v2] changes to increase xxhash' configurability when inlining it

- xxhash.c
- xxhsum.1
- xxhsum.1.md
I was doing some cleanup of some company code and noticed that I should  share this upstream. Thank you for sharing your code to the world.
(Note I wanted to fix endianess to endianness but did not. Maybe consider that also.)
> few typo fixes in comments or docs

- Makefile
- xxhsum.1.md
> Revert "Remove trailing whitespace with a check/test."

- index.html
> Add pure php implementation

- .gitignore
- Makefile
- xxhsum.c
and minor `Makefile` optimizations
> Fix compilation under msys2

- xxh3.h
Signed-off-by: easyaspi314 (Devin) <easyaspi314@users.noreply.github.com>
> xxh3: add NEON support

- xxh3.h
> Revert "Improve aarch64 performance"

- xxh3.h
The NEON algorithms have now been updated to match the SSE2 algorithm.
> Update ARM NEON code

- xxhsum.c
- xxhsum now prints more professional-looking error messages:
Before:
```
Pb opening foo
```
After:
```
Error: Could not open 'foo': No such file or directory.
```
- xxhsum will now attempt to display the architecture and the compiler version in the benchmark WELCOME_MESSAGE.
It detects the following compilers:
- Clang
- GCC
- Intel Compiler
- MSVC
- tcc  
and it should detect the following architectures:
- x86 (+SSE2/AVX/AVX2)
- x86_64 (+SSE2/AVX/AVX2)
- ARM (+NEON)
- aarch64
- PowerPC 64
- PowerPC
- AVR
- MIPS 64
- MIPS
Before:
```
./xxhsum 0.7.0 (64-bits little endian), by Yann Collet
```
After:
```
./xxhsum 0.7.0 (64-bits x86_64 + SSE2 little endian), GCC 8.3.0, by Yann Collet
```
- Sanity checks are consistent now and give better warning messages:
Before:
```
ERROR : Test  1 : …
```
> Improve xxhsum output message quality

- README.md
- xxhash.h
> Fixed the 'dllimport' build issue with MSVC.

- xxh3.h
> xxh3 neon fix

- xxh3.h
- xxhsum.c
Supports both big and little endian.
> Port over the VSX version

- appveyor.yml
- xxh3.h
fix #220 ,
and adds a test for this compilation target on Appveyor (suggested by @v-strob).
> Fix Visual compilation for ARM target

- appveyor.yml
added : 
- clang tests
- visual x86+x64 runtime tests
- visual ARM64 tests
- visual 2013 and 2017 tests
> Update AppveyorCI tests

- .travis.yml
- Makefile
- cmake_unofficial/CMakeLists.txt
> add cmake test to Travis CI

- cmake_unofficial/CMakeLists.txt
- cmake_unofficial/README.md
- cmake_unofficial/xxHashConfig.cmake.in
Hello!
Patch allows easy integration within downstream CMake projects and fixes some issues of BUNDLED_MODE.
Unfortunately it requires CMake 3.13 but i dont think that is a realy big deal.
Have a good day!
> Add CMake Config.

- LICENSE
to reflect the different terms
for the library (BSD-2)
and the command line interface (GPLv2),
answering #253 .
> updated LICENSE

- Makefile
- xxhsum.c
> xxhsum -q does no longer display "Loading" notification

- xxh3.h
It's a start, but an improvement. I still have more things I would like
to change but it is good for now.
> Try to improve some variable names.

- xxh3.h
The previous XXH3_accumulate_512 loop didn't fare well since XXH128
started swapping the addition.
Neither GCC nor Clang could follow the barely-readable loop, resulting
in garbage code output.
This made XXH3 much slower. Take 32-bit scalar ARM.
Ignoring loads and potential interleaving optimizations, in the main
loop, XXH32 takes 16 cycles for 8 bytes on a typical ARMv6+ CPU, or 2 cpb.
```asm
mla     r0, r2, r5, r0  @ 4 cycles
ror     r0, r0, #19     @ 1 cycle
mul     r0, r0, r6      @ 3 cycles
mla     r1, r3, r5, r1  @ 4 cycles
ror     r1, r1, #19     @ 1 cycle
mul     r1, r1, r6      @ 3 cycles
```
XXH3_64b takes 9, or 1.1 cpb:
```asm
adds    r0, r0, r2      @ 2 cycles
adc     r1, r1, r3      @ 1 cycle
eor     r4, r4, r2      @ 1 cycle
eor     r5, r5, r3      @ 1 cycle
umlal   r0, r1, …
```
> [SCALAR] Improve scalar XXH3_accumulate_512 loop

- Makefile
- xxhsum.1
- xxhsum.1.md
so that it better reflects advanced functionalities.
fix #286
Reported by @LEARAX
> updated man page

- CHANGELOG
- Makefile
- README.md
- appveyor.yml
- cmake_unofficial/README.md
- doc/xxhash_spec.md
- tests/Makefile
- tests/bench/Makefile
- tests/bench/bhDisplay.h
- tests/bench/hashes.h
- tests/bench/main.c
- tests/collisions/README.md
- tests/collisions/allcodecs/dummy.c
- tests/collisions/allcodecs/dummy.h
- tests/collisions/main.c
- tests/collisions/sort.cc
- tests/collisions/sort.hh
- tests/multiInclude.c
- xxh3.h
- xxhash.h
- xxhsum.c
Finish what #319 started.
Not perfect, but should be good enough.
Also documented a few extra things like `doubleSecret`, `XXH_mult32to64`,  and the `clock()` issue in `BMK_benchHash`
> The Great Typo Hunt, Chapter 2

- js/bootstrap-patch.css
Fix the awkward navbar on mobile:
> [Website] Fix navbar on mobile

- xxhsum.c
following suggestions from #345.
Note : only cosmetic changes in this diff,
I've avoided any change that would impact the behavior of the program.
> Improved help message

- xxh3.h
- xxhash.h
> support for secretSize > 4 GB in streaming mode

- .travis.yml
- xxh3.h
- xxhash.h
initial PR from @gzm55,
fix some conflicts 
added minor style changes and tests
supersedes #351
> Vectorized initCustomSecret()

- xxh3.h
- xxhash.h
- xxhsum.c
created `XXH3_generateSecret()`,
answering #361 .
updated documentation and added corresponding test.
> Key Derivation function

- Makefile
compatible with all sub-versions of cygwin
fix #356
> added make install target for cygwin

- xxh3.h
- xxhsum.c
note :
I was unable to reproduce the speed issue on my own platforms (laptop, desktop, macos, ubuntu).
Therefore, @easyaspi314, could you test that this patch solves your performance issue ?
The fix feels logical enough, and doesn't negatively impact performance either, so even if I can't observe performance benefits directly, it's good to go.
Perhaps more importantly : 
this patch also fixes `XXH128_withSecret()`,
which was messed up with default `kSecret`.
The error remained unnoticed because there was no self-test for this variant.
Therefore, also added a test in `xxhsum` checking results of `XXH128_withSecret()`
> fixed performance issue reported in #398
